[package]
name = "nokhwa"
version = "0.1.0-1"
authors = ["l1npengtul <l1npengtul@protonmail.com>"]
edition = "2018"
description = "A Simple to use, cross platform Rust Webcam Capture Library"
license = "MPL-2.0"
repository = "https://github.com/l1npengtul/nokhwa"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
input_uvc = ["uvc", "uvc/vendor"]
input_v4l = ["v4l"]
docs-only = ["input_uvc", "input_v4l"]

[dependencies]
thiserror = "1.0.24"
image = "0.23.14"
mozjpeg = "0.8.24"
ouroboros = "0.9.3"
flume = "0.10.5"

[dependencies.v4l]
version = "0.12.1"
optional = true

[dependencies.uvc]
version = "0.2.0"
optional = true

[package.metadata.docs.rs]
no-default-features = true
features = ["docs-only"]