[package]
name = "nokhwa"
version = "0.3.1"
authors = ["l1npengtul <l1npengtul@protonmail.com>"]
edition = "2018"
description = "A Simple-to-use, cross-platform Rust Webcam Capture Library"
keywords = ["camera", "webcam", "capture", "cross-platform"]

license = "MPL-2.0"
repository = "https://github.com/l1npengtul/nokhwa"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
input-uvc = ["uvc", "uvc/vendor", "ouroboros"]
input-v4l = ["v4l"]
input-opencv = ["opencv", "opencv/clang-runtime"]
input-ipcam = ["input-opencv"]
input-gst = ["gstreamer", "glib", "gstreamer-app", "gstreamer-video", "regex"]
output-wgpu = ["wgpu"]
docs-only = ["input-uvc", "input-v4l", "input-opencv", "input-ipcam", "input-gst", "output-wgpu"]
docs-nolink = ["glib/dox", "gstreamer-app/dox", "gstreamer/dox", "gstreamer-video/dox", "opencv/docs-only"]

[dependencies]
thiserror = "1.0.24"
image = "0.23.14"
mozjpeg = "0.8.24"
flume = "0.10.5"
usb_enumeration = "0.1.2"
paste = "1.0.5"

[dependencies.v4l]
version = "0.12.1"
optional = true

[dependencies.ouroboros]
version = "0.10.0"
optional = true

[dependencies.uvc]
version = "0.2.0"
optional = true

[dependencies.wgpu]
version = "0.9.0"
optional = true

[dependencies.opencv]
version = "0.53.0"
features = ["clang-runtime"]
optional = true

#[dependencies.nokhwa-bindings-windows]
#version = "0.1.0"
#optional = true

[dependencies.gstreamer]
version = "0.17.0"
optional = true

[dependencies.gstreamer-app]
version = "0.17.0"
optional = true

[dependencies.gstreamer-video]
version = "0.17.0"
optional = true

[dependencies.glib]
version = "0.14.0"
optional = true

[dependencies.regex]
version = "1.4.6"
optional = true


[package.metadata.docs.rs]
no-default-features = true
features = ["docs-only", "docs-nolink"]