[package]
name = "nokhwa"
version = "0.1.0-1"
authors = ["l1npengtul <l1npengtul@protonmail.com>"]
edition = "2018"
description = "A WIP Cross Platform Rust Library for powerful Webcam Capture and Virtual Webcams"
license = "MPL-2.0"
repository = "https://github.com/l1npengtul/nokhwa"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
input_uvc = ["uvc"]
input_opencv = ["opencv", "opencv/clang-runtime"]
input_msmf = ["windows"]
input_v4l = ["v4l"]
input_gstreamer = ["gstreamer"]
input_ffmpeg = []
docs-only = ["input_uvc", "input_opencv", "input_msmf", "input_v4l", "input_gstreamer", "input_ffmpeg"]

[dependencies]
thiserror = "1.0.24"
image = "0.23.14"
mozjpeg = "0.8.24"

[dependencies.opencv]
version = "0.53.0"
optional = true

[dependencies.v4l]
version = "0.12.1"
optional = true

[dependencies.uvc]
version = "0.2.0"
optional = true

[dependencies.gstreamer]
version = "0.16.7"
optional = true

[dependencies.windows]
version = "0.10.0"
optional = true

[dev-dependencies.windows]
version = "0.10.0"

[package.metadata.docs.rs]
no-default-features = true
features = ["docs-only"]