[package]
name = "capture"
version = "0.1.0"
authors = ["l1npengtul <l1npengtul@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
glium = "0.30.0"
glutin = "0.27.0"
flume = "0.10.7"

# Use these as you need
[dependencies.nokhwa]
path = "../../../nokhwa"
features = ["docs-only"]
