[package]
name = "nokhwa-bindings-windows"
version = "0.1.0"
authors = ["l1npengtul"]
edition = "2018"
description = "The Windows binding crate for `nokhwa` so crates.io won't reject my builds, please don't use this (unless you are developing `nokhwa`)"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["windows"]
docs-only = [] # please don't try to build this

[dependencies]

[dependencies.windows]
version = "0.10.0"
optional = true


[build-dependencies.windows]
version = "0.10.0"

[package.metadata.docs.rs]
no-default-features = true
features = ["docs-only"]