[package]
name = "nokhwa-bindings-windows"
version = "0.1.0"
authors = ["l1npengtul"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "The Windows binding crate for `nokhwa` so crates.io won't reject my builds, please don't use this (unless you are developing `nokhwa`) You dont actually have to do any crediting or anything, just please dont use this."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
docs-only = [] # please don't try to build this

[dependencies]
once_cell = "1.8.0"
thiserror = "1.0.26"
lazy_static = "1.4.0"

[build-dependencies]
bindgen = "0.58.1"
cc = "1.0.69"

[package.metadata.docs.rs]
no-default-features = true
features = ["docs-only"]