[package]
name = "nokhwa-bindings-windows"
version = "0.2.3"
authors = ["l1npengtul"]
edition = "2018"
license = "MPL-2.0"
repository = "https://github.com/l1npengtul/nokhwa"
description = "The Windows Media Foundation bindings crate for `nokhwa`"
keywords = ["media-foundation", "windows", "capture"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.26"

[target.'cfg(all(target_os = "windows", windows))'.dependencies.windows]
version = "0.20.0"

[target.'cfg(all(target_os = "windows", windows))'.build-dependencies.windows]
version = "0.20.0"
