[package]
name = "nokhwa-bindings-windows"
version = "0.2.0"
authors = ["l1npengtul"]
edition = "2018"
license = "MPL-2.0"
repository = "https://github.com/l1npengtul/nokhwa"
description = "The Windows Media Foundation bindings crate for `nokhwa`"
keywords = ["media-foundation", "windows", "capture"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["windows"]
docs-only = [] # please don't try to build this

[dependencies]
thiserror = "1.0.26"

[dependencies.windows]
version = "0.17.2"
optional = true

[build-dependencies]

[target.'cfg(windows)'.build-dependencies]
windows = "0.17.2"

[package.metadata.docs.rs]
no-default-features = true
features = ["docs-only"]